openapi: 3.1.0
servers:
  - url: "/1.0/"
info:
  title: Universal Resolver
  description: Universal Resolver
  version: 1.0.1
  contact:
    name: Decentralized Identity Foundation
    email: markus@danubetech.com
paths:
  "/identifiers/{identifier}":
    get:
      summary: Resolve a DID / Dereference a DID URL
      description: <p>This endpoint resolves a DID or dereferences a DID URL. As input it takes the
        DID or DID URL, plus resolution options or dereferencing options.
        The output is a DID document plus
        metadata. The same endpoint can also be used to dereference a DID URL. In
        this case, the output is a DID document, or part of a DID document, or some
        other resource identified by the DID URL.</p>
        <p>See the <a href="<a href="https://www.w3.org/TR/did-resolution/">DID
        Resolution</a> specification for additional details.</p>
      operationId: resolve
      tags:
        - Universal Resolver
      parameters:
        - in: path
          required: true
          name: identifier
          schema:
            type: string
          description: The DID to be resolved, or the DID URL to be dereferenced.
          examples:
            example1:
              value: did:indy:sovrin:builder:VbPQNHsvoLZdaNU7fTBeFx
              description: A DID using the `indy` method.
            example2:
              value: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
              description: A DID using the `ion` method.
            example3:
              value: did:ebsi:z25ZZFS7FweHsm9MX2Qvc6gc
              description: A DID using the `ebsi` method.
            example4:
              value: did:indy:sovrin:builder:VbPQNHsvoLZdaNU7fTBeFx#key-1
              description: A DID URL with a fragment.
            example5:
              value: did:ebsi:z25ZZFS7FweHsm9MX2Qvc6gc#keys-1
              description: A DID URL with a fragment.
        - in: header
          required: false
          name: Accept
          schema:
            type: string
          description: The requested media type of the DID document representation or
            DID resolution result.
          examples:
            application/did:
              value: application/did
              description: Media type of a DID document.
            application/did-resolution:
              value: application/did-resolution
              description: Media type of a DID resolution result.
            application/did-url-dereferencing:
              value: application/did-url-dereferencing
              description: Media type of a DID URL dereferencing result.
        - in: query
          name: options
          schema:
            type: object
            additionalProperties:
              type: string
          description: The options for resolving the DID or dereferencing the DID URL.
          style: form
          explode: true
      responses:
        "200":
          description: successfully resolved!
          content:
            application/did:
              schema:
                type: object
                description: The DID document.
                example:
                  "@context": https://www.w3.org/ns/did/v1.1
                  id: did:indy:sovrin:WRfXPg8dantKVubE3HX8pw
                  verificationMethod:
                    - id: did:indy:sovrin:WRfXPg8dantKVubE3HX8pw#key-1
                      type: Ed25519VerificationKey2018
                      publicKeyBase58: H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV
            application/did-resolution:
              schema:
                $ref: "#/components/schemas/ResolutionResult"
            application/did-url-dereferencing:
              schema:
                $ref: "#/components/schemas/DereferencingResult"
        "400":
          description: Invalid DID or DID URL.
        "404":
          description: DID or DID URL not found.
        "406":
          description: Representation not supported.
        "410":
          description: Successfully resolved, but DID is deactivated.
          content:
            application/did:
              schema:
                type: object
                description: The deactivated DID document.
            application/did-resolution:
              schema:
                $ref: "#/components/schemas/ResolutionResult"
            application/did-url-dereferencing:
              schema:
                $ref: "#/components/schemas/DereferencingResult"
        "500":
          description: Internal Error.
        "501":
          description: DID method not supported.
  "/properties":
    get:
      summary: Return a map of configuration properties
      description: <p>This endpoint returns a map of the configuration properties
        of the DID Resolver, including of its drivers.</p>
      operationId: universalResolverGetProperties
      tags:
        - Universal Resolver
      responses:
        "200":
          description: Success.
          content:
            application/did+json:
              schema:
                type: object
                description: A map of properties.
                example:
                  indy:
                    libIndyPath: "/lib"
                    poolConfigs: "..."
  "/methods":
    get:
      summary: Return a list of supported DID methods
      description: <p>This endpoint returns a list of DID methods supported by the
        DID Resolver.</p>
      operationId: universalResolverGetMethods
      tags:
        - Universal Resolver
      responses:
        "200":
          description: Success.
          content:
            application/did+json:
              schema:
                type: array
                items:
                  type: string
                description: The list of supported DID methods.
                example:
                  - btcr
                  - indy
                  - v1
                  - key
  "/testIdentifiers":
    get:
      summary: Return a map of test identifiers
      description: <p>This endpoint returns a map of test identifiers, grouped by
        DID method.</p>
      operationId: universalResolverGetTestIdentifiers
      tags:
        - Universal Resolver
      responses:
        "200":
          description: Success.
          content:
            application/did+json:
              schema:
                type: object
                description: A map of test identifiers, grouped by DID method.
                example:
                  btcr:
                    - did:btcr:xz35-jznz-q9yu-ply
                    - did:btcr:xkrn-xz7q-qsye-28p
                  indy:
                    - did:indy:sovrin:WRfXPg8dantKVubE3HX8pw
  "/traits":
    get:
      summary: Return a map of DID traits
      description: <p>This endpoint returns a map of the DID traits of
        the DID methods supported by the DID Resolver.</p>
      operationId: universalResolverGetTraits
      tags:
        - Universal Resolver
      responses:
        "200":
          description: Success.
          content:
            application/did+json:
              schema:
                type: object
                description: A map of DID traits.
                example:
                  indy:
                    updatable: true
                    deactivatable: true
                    enumerable: true
                    historyAvailable: true
                    humanReadable: false
components:
  schemas:
    ResolutionResult:
      description: The DID resolution result.
      type: object
      properties:
        didDocument:
          type: object
        didResolutionMetadata:
          type: object
          additionalProperties: { }
        didDocumentMetadata:
          type: object
          additionalProperties: { }
    DereferencingResult:
      description: The DID URL dereferencing result.
      type: object
      properties:
        content:
          type: object
        dereferencingMetadata:
          type: object
          additionalProperties: { }
        contentMetadata:
          type: object
          additionalProperties: { }
